import Head from "next/head";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import type { Metadata } from "next";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { GetStaticPropsContext } from 'next';
import { Header, Hero, GettingStarted, Layout } from "@/components";


export const metadata: Metadata = {
  title: "My Quiz App",
  description: "Check your knowledge",
};

export default function Home() {
  
  return (
    <>
      <Head>
        <title>JSQuiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero/>
        <GettingStarted/>
      </Layout>
    </>
  );
}


export async function getStaticProps({ locale } : GetStaticPropsContext) {
	return {
	  props: {
		...(await serverSideTranslations(locale ?? 'en', ['common'])),
	  },
	}
  }